### PR TITLE
prefetch support

### PR DESCRIPTION
**Pull request by tjmehta**
Added prefetch options support for the consumer channel

### CODE REVIEW

**Comment by tjmehta** [comment]
closes #38

**Comment by tjmehta** [comment]
closes #39

**Comment by spencerapplegate** [comment]
@tjmehta this is great! Thank you for reacting so quickly to this. In the future it may provide some value to users to wrap other channel methods available through amqplib too like queue and exchange controls.

**Comment by tjmehta** [comment]
@spencerapplegate no problem! Let me know if you hit anything else and we can definitely add it

**Pull request merged**
